#cloud-config
package_update: true
package_upgrade: true
write_files:
  - content: |
      [Service]
      Environment="KUBELET_EXTRA_ARGS=--cloud-provider=external"
    path: /etc/systemd/system/kubelet.service.d/20-hetzner-cloud.conf
  - content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd
    path: /etc/systemd/system/docker.service.d/00-cgroup-systemd.conf
  - content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.ipv6.conf.default.forwarding = 1
    path: /etc/sysctl.conf
apt:
  preserve_sources_list: true
  sources:
    docker:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    kubernetes:
      source: deb http://packages.cloud.google.com/apt/ kubernetes-xenial main
      keyid: 59FE0256827269DC81578F928B57C5C2836F4BEB
packages:
  - docker-ce
  - kubeadm
  - kubectl
  - kubelet
