- name: Initialize kubeadm master nodes
  shell: >
    kubeadm init
    --pod-network-cidr=10.244.0.0/16
    --kubernetes-version=v1.21.0
    >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: ensure kubeconfig directory exists
  ansible.builtin.file:
    dest: ~/.kube
    state: directory

- name: copy kubeconfig to ~/.kube/config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: yes

- name: fetch ~/.kube/config
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: kubeconfig
    flat: yes

- name: Install pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_created.txt
  args:
    chdir: $HOME
    creates: pod_network_created.txt

- name: patch flannel deployment to run on unintialized nodes
  shell: kubectl -n kube-system patch ds kube-flannel-ds --type json -p '[{"op":"add","path":"/spec/template/spec/tolerations/-","value":{"key":"node.cloudprovider.kubernetes.io/uninitialized","value":"true","effect":"NoSchedule"}}]'

- name: install hetzner tokens
  shell: "kubectl -n kube-system create secret generic hcloud --from-literal=token={{hcloud_token}} >> tokens_created.txt"
  args:
    chdir: $HOME
    creates: tokens_created.txt

- name: install hetzner ccm
  shell: kubectl apply -f  https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/master/deploy/ccm.yaml >> ccm_installed.txt
  args:
    chdir: $HOME
    creates: ccm_installed.txt

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
