---
- hosts: 127.0.0.1
  pre_tasks:
    - name: convert ssh_key from dos 2 unix
      template:
        src: ./ssh_key_terraform
        dest: ./ssh_key
- hosts: all
  roles:
    - role: configuration
      tags:
        - configuration
    - role: installation
      tags:
        - installation
- hosts: master
  roles:
    - role: kubeadm-init
      tags:
        - kubeadm
        - init
- hosts: worker
  roles:
    - role: kubeadm-join
      tags:
        - kubeadm
        - join
